version: '3.8'

services:
  bloodconnect:
    build: .
    container_name: bloodconnect-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env.prod
    restart: unless-stopped