# Disable H2 Console
spring.h2.console.enabled=false

# Neon PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://ep-polished-heart-aonps7sm-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_vzCN90KbehtF&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vzCN90KbehtF
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:6f5A9e2B4c7D1e4F8a0B3c6D9e2F5a8B1c4D7e0F3a6B9c2D5e8F1a4B7c0F3a6B}

spring.jackson.default-property-inclusion=non_null

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-json