# Disable H2 Console
spring.h2.console.enabled=false

spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}

spring.jackson.default-property-inclusion=non_null

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-json

spring.datasource.hikari.minimum-idle=0

spring.datasource.hikari.maximum-pool-size=5

spring.datasource.hikari.idle-timeout=60000

spring.datasource.hikari.max-lifetime=1800000