-- ============================================================================
-- 1. INSERT USERS (50 Entries)
-- ============================================================================

INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available,
 last_donation_date, is_active, created_at) VALUES ('Admin One', 'admin1@bloodconnect.com',
 '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 32, '9876543210', 'O_POS', 'Mumbai', 'Admin HQ, Andheri West', 'INDIVIDUAL', 'ADMIN', false, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available,
 last_donation_date, is_active, created_at) VALUES ('Admin Two', 'admin2@bloodconnect.com',
 '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 29, '9876543211', 'A_POS', 'Mumbai', 'Admin HQ, Andheri West', 'INDIVIDUAL', 'ADMIN', false, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available,
 last_donation_date, is_active, created_at) VALUES ('Admin Three', 'admin3@bloodconnect.com',
 '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 35, '9876543212', 'B_POS', 'Mumbai', 'Admin HQ, Andheri West', 'INDIVIDUAL', 'ADMIN', false, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available,
 last_donation_date, is_active, created_at) VALUES ('Admin Four', 'admin4@bloodconnect.com',
 '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 41, '9876543213', 'AB_POS', 'Mumbai', 'Admin HQ, Andheri West', 'INDIVIDUAL', 'ADMIN', false, NULL, true, CURRENT_TIMESTAMP);

INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Red Cross Blood Trust', 'contact@redcrossmumbai.org', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 10, '2228471920', 'O_NEG', 'Mumbai', 'Red Cross Building, Colaba', 'ORGANIZATION', 'USER', false, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('City Care Hospital', 'info@citycareblood.org', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 15, '4428941022', 'A_NEG', 'Chennai', '12, Greams Road', 'ORGANIZATION', 'USER', false, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Metro Health Foundation', 'bloodbank@metrohealth.org', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 8, '1149582011', 'B_NEG', 'Delhi', 'Connaught Place, Block E', 'ORGANIZATION', 'USER', false, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Lifeline Charitable Trust', 'donate@lifelinehyd.org', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 5, '4029481023', 'AB_NEG', 'Hyderabad', 'Gachibowli Main Rd', 'ORGANIZATION', 'USER', false, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Apex Blood Center', 'apexblood@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 12, '8029481921', 'O_POS', 'Bengaluru', 'MG Road, Next to Metro', 'ORGANIZATION', 'USER', false, NULL, true, CURRENT_TIMESTAMP);

INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Aarav Sharma', 'aarav.sharma@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 24, '9812345670', 'A_POS', 'Delhi', 'H-23, Rajouri Garden', 'INDIVIDUAL', 'USER', true, '2026-01-15', true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Aditya Patel', 'aditya.patel@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 28, '9812345671', 'O_POS', 'Mumbai', '45, Linking Road, Bandra', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Ananya Iyer', 'ananya.iyer@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 22, '9812345672', 'B_POS', 'Chennai', 'Plot 4, Adyar', 'INDIVIDUAL', 'USER', true, '2025-12-20', true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Arjun Reddy', 'arjun.reddy@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 31, '9812345673', 'O_NEG', 'Hyderabad', 'Jubilee Hills, Road No 36', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Dia Sen', 'dia.sen@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 26, '9812345674', 'AB_POS', 'Kolkata', 'Salt Lake, Sector 3', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Ishaan Verma', 'ishaan.verma@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 35, '9812345675', 'A_NEG', 'Delhi', 'Pocket C, Vasant Kunj', 'INDIVIDUAL', 'USER', false, '2026-04-10', true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Kavya Nair', 'kavya.nair@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 29, '9812345676', 'B_NEG', 'Bengaluru', 'Indiranagar, 100ft Rd', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Kabir Mehta', 'kabir.mehta@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 45, '9812345677', 'O_POS', 'Ahmedabad', 'Satellite Area', 'INDIVIDUAL', 'USER', true, '2026-02-28', true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Meera Joshi', 'meera.joshi@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 33, '9812345678', 'A_POS', 'Pune', 'Kothrud, Ideal Colony', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Pranav Rao', 'pranav.rao@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 27, '9812345679', 'O_POS', 'Bengaluru', 'Whitefield', 'INDIVIDUAL', 'USER', false, NULL, false, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Rohan Das', 'rohan.das@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 23, '9812345680', 'B_POS', 'Kolkata', 'Ballygunge Place', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Riya Kapoor', 'riya.kapoor@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 30, '9812345681', 'AB_NEG', 'Mumbai', 'Worli Sea Face', 'INDIVIDUAL', 'USER', true, '2026-03-05', true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Siddharth Malhotra', 'sid.m@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 38, '9812345682', 'O_NEG', 'Delhi', 'Saket, Block J', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Sanya Gupta', 'sanya.g@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 25, '9812345683', 'A_POS', 'Jaipur', 'C-Scheme', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Tejas Kulkarni', 'tejas.k@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 29, '9812345684', 'B_POS', 'Pune', 'Viman Nagar', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Utkarsh Mishra', 'utkarsh.m@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 34, '9812345685', 'O_POS', 'Lucknow', 'Hazratganj', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Vedika Hegde', 'vedika.h@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 26, '9812345686', 'A_NEG', 'Mumbai', 'Mulund East', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Yash Choudhary', 'yash.c@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 31, '9812345687', 'AB_POS', 'Indore', 'Vijay Nagar', 'INDIVIDUAL', 'USER', false, NULL, false, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Zoya Khan', 'zoya.k@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 28, '9812345688', 'O_POS', 'Hyderabad', 'Banjara Hills', 'INDIVIDUAL', 'USER', true, '2026-05-01', true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Alok Mishra', 'alok.m@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 40, '9812345689', 'B_POS', 'Kanpur', 'Swaroop Nagar', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Bhavana Rao', 'bhavana.r@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 27, '9812345690', 'A_POS', 'Chennai', 'Velachery', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Chirag Paswan', 'chirag.p@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 33, '9812345691', 'O_NEG', 'Patna', 'Kankarbagh', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Divya Dutta', 'divya.d@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 29, '9812345692', 'AB_NEG', 'Chandigarh', 'Sector 15', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Gaurav Taneja', 'gaurav.t@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 36, '9812345693', 'O_POS', 'Delhi', 'Dwarka Sector 10', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Harshita Jain', 'harshita.j@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 24, '9812345694', 'B_POS', 'Jaipur', 'Malviya Nagar', 'INDIVIDUAL', 'USER', false, NULL, false, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Karan Johar', 'karan.j@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 42, '9812345695', 'A_POS', 'Mumbai', 'Lokhandwala', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Lipika Samanta', 'lipika.s@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 31, '9812345696', 'O_POS', 'Bhubaneswar', 'Patia', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Manish Malhotra', 'manish.m@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 39, '9812345697', 'AB_POS', 'Mumbai', 'Juhu', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Nisha Pillai', 'nisha.p@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 28, '9812345698', 'B_NEG', 'Kochi', 'Kakkanad', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Omkar Shetty', 'omkar.s@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 35, '9812345699', 'O_POS', 'Mangaluru', 'Kadri', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Pooja Hegde', 'pooja.h@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 26, '9812345700', 'A_POS', 'Hyderabad', 'Gachibowli', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Rahul Dravid', 'rahul.d@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 48, '9812345701', 'O_POS', 'Bengaluru', 'Indiranagar', 'INDIVIDUAL', 'USER', true, '2026-03-12', true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Shreya Ghoshal', 'shreya.g@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 34, '9812345702', 'AB_POS', 'Kolkata', 'Behala', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Tarun Tahiliani', 'tarun.t@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 44, '9812345703', 'B_POS', 'Delhi', 'Mehrauli', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Ujjwal Singh', 'ujjwal.s@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 23, '9812345704', 'O_NEG', 'Patna', 'Boring Road', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Varun Dhawan', 'varun.d@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 32, '9812345705', 'A_POS', 'Mumbai', 'Juhu scheme', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Yami Gautam', 'yami.g@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 30, '9812345706', 'B_POS', 'Chandigarh', 'Sector 35', 'INDIVIDUAL', 'USER', false, NULL, false, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Abhinav Bindra', 'abhinav.b@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 37, '9812345707', 'O_POS', 'Zirakpur', 'Highland Marg', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Deepika Padukone', 'deepika.p@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 38, '9812345708', 'O_POS', 'Bengaluru', 'Malleswaram', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Ranveer Singh', 'ranveer.s@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 39, '9812345709', 'B_POS', 'Mumbai', 'Bandra', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);
INSERT INTO users (full_name, email, password, age, phone, blood_group, city, address, account_type, role, is_available, last_donation_date, is_active, created_at) VALUES ('Alia Bhatt', 'alia.b@gmail.com', '$2a$10$bk3c37zG7QsR8pqzCNL2eO2DSimQ8/Gvo2vKoI3vwptq.EAF3Lxn.', 29, '9812345710', 'A_POS', 'Mumbai', 'Juhu', 'INDIVIDUAL', 'USER', true, NULL, true, CURRENT_TIMESTAMP);


-- ============================================================================
-- 2. INSERT BLOOD REQUESTS (30 Entries)
-- ============================================================================

INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'aarav.sharma@gmail.com'), 'A_POS', 'Delhi', 'URGENT', 'OPEN', 'Emergency heart surgery requirement.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'ananya.iyer@gmail.com'), 'B_POS', 'Chennai', 'CRITICAL', 'OPEN', 'Thalassemia major patient needs blood urgently.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'dia.sen@gmail.com'), 'AB_POS', 'Kolkata', 'NORMAL', 'OPEN', 'Scheduled surgery next week.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'kavya.nair@gmail.com'), 'B_NEG', 'Bengaluru', 'CRITICAL', 'OPEN', 'Accident emergency case.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'meera.joshi@gmail.com'), 'A_POS', 'Pune', 'URGENT', 'OPEN', 'Post-pregnancy complications.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'contact@redcrossmumbai.org'), 'O_NEG', 'Mumbai', 'NORMAL', 'OPEN', 'Stock needed for blood bank.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'info@citycareblood.org'), 'A_NEG', 'Chennai', 'URGENT', 'OPEN', 'Hospital deficit for rare group.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'bloodbank@metrohealth.org'), 'B_NEG', 'Delhi', 'CRITICAL', 'OPEN', 'ICU requirement.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'rohan.das@gmail.com'), 'B_POS', 'Kolkata', 'NORMAL', 'OPEN', 'Routine plasma exchange.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'sanya.g@gmail.com'), 'A_POS', 'Jaipur', 'NORMAL', 'OPEN', 'Anemia patient treatment.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'tejas.k@gmail.com'), 'B_POS', 'Pune', 'URGENT', 'OPEN', 'Severe Dengue platelet requirement.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'utkarsh.m@gmail.com'), 'O_POS', 'Lucknow', 'CRITICAL', 'OPEN', 'Emergency trauma unit.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'vedika.h@gmail.com'), 'A_NEG', 'Mumbai', 'NORMAL', 'OPEN', 'Cancer patient chemotherapy support.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'alok.m@gmail.com'), 'B_POS', 'Kanpur', 'URGENT', 'OPEN', 'Gastrointestinal bleeding emergency.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'bhavana.r@gmail.com'), 'A_POS', 'Chennai', 'NORMAL', 'OPEN', 'Bone marrow transplant pre-op.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'chirag.p@gmail.com'), 'O_NEG', 'Patna', 'CRITICAL', 'OPEN', 'Road accident multiple fractures.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'divya.d@gmail.com'), 'AB_NEG', 'Chandigarh', 'URGENT', 'OPEN', 'High urgency platelette request.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'gaurav.t@gmail.com'), 'O_POS', 'Delhi', 'NORMAL', 'OPEN', 'Scheduled bypass surgery.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'lipika.s@gmail.com'), 'O_POS', 'Bhubaneswar', 'URGENT', 'OPEN', 'Dialysis patient drop in hemoglobin.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'nisha.p@gmail.com'), 'B_NEG', 'Kochi', 'CRITICAL', 'OPEN', 'Emergency delivery case.', CURRENT_TIMESTAMP);

INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'aditya.patel@gmail.com'), 'O_POS', 'Mumbai', 'URGENT', 'FULFILLED', 'Urgent requirement resolved.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'arjun.reddy@gmail.com'), 'O_NEG', 'Hyderabad', 'CRITICAL', 'FULFILLED', 'Received matching donor timely.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'kabir.mehta@gmail.com'), 'O_POS', 'Ahmedabad', 'NORMAL', 'FULFILLED', 'Fulfilled via local donor unit.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'pooja.h@gmail.com'), 'A_POS', 'Hyderabad', 'URGENT', 'FULFILLED', 'Resolved by volunteer.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'shreya.g@gmail.com'), 'AB_POS', 'Kolkata', 'NORMAL', 'FULFILLED', 'Fulfilled successfully.', CURRENT_TIMESTAMP);

INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'sid.m@gmail.com'), 'O_NEG', 'Delhi', 'CRITICAL', 'CANCELLED', 'Arranged from family member.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'omkar.s@gmail.com'), 'O_POS', 'Mangaluru', 'NORMAL', 'CANCELLED', 'Patient discharged.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'tarun.t@gmail.com'), 'B_POS', 'Delhi', 'URGENT', 'CANCELLED', 'Alternative arrangements done.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'ujjwal.s@gmail.com'), 'O_NEG', 'Patna', 'NORMAL', 'CANCELLED', 'Not needed anymore.', CURRENT_TIMESTAMP);
INSERT INTO blood_requests (requester_id, blood_group, city, urgency_level, status, message, created_at) VALUES ((SELECT id FROM users WHERE email = 'varun.d@gmail.com'), 'A_POS', 'Mumbai', 'CRITICAL', 'CANCELLED', 'Procured from direct blood bank.', CURRENT_TIMESTAMP);


-- ============================================================================
-- 3. INSERT DONATION OFFERS (40 Entries)
-- ============================================================================

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'gaurav.t@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Delhi' AND blood_group = 'A_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'bhavana.r@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Delhi' AND blood_group = 'A_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'rohan.das@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Chennai' AND blood_group = 'B_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'tejas.k@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Chennai' AND blood_group = 'B_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'nisha.p@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Bengaluru' AND blood_group = 'B_NEG' LIMIT 1), 'ACCEPTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'meera.joshi@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Pune' AND blood_group = 'A_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'alia.b@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Pune' AND blood_group = 'A_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'chirag.p@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Mumbai' AND blood_group = 'O_NEG' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'sid.m@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Mumbai' AND blood_group = 'O_NEG' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'ishaan.verma@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Chennai' AND blood_group = 'A_NEG' LIMIT 1), 'DECLINED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'aditya.patel@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Lucknow' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'kabir.mehta@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Lucknow' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'deepika.p@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Lucknow' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'alok.m@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Kanpur' AND blood_group = 'B_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'aditya.patel@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Delhi' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'kabir.mehta@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Delhi' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'lipika.s@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Bhubaneswar' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'nisha.p@gmail.com'), (SELECT id FROM blood_requests WHERE city = 'Kochi' AND blood_group = 'B_NEG' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'deepika.p@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'FULFILLED' AND blood_group = 'O_POS' LIMIT 1), 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'aditya.patel@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'FULFILLED' AND blood_group = 'O_POS' LIMIT 1), 'DECLINED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'arjun.reddy@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'FULFILLED' AND blood_group = 'O_NEG' LIMIT 1), 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'alia.b@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'FULFILLED' AND blood_group = 'A_POS' LIMIT 1), 'ACCEPTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'arjun.reddy@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'CANCELLED' AND blood_group = 'O_NEG' LIMIT 1), 'CANCELLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'alia.b@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'CANCELLED' AND blood_group = 'A_POS' LIMIT 1), 'CANCELLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'ranveer.s@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'B_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'varun.d@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'A_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'karan.j@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'A_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'manish.m@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'AB_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'shreya.g@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'AB_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'zoya.k@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'rahul.d@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'omkar.s@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'O_POS' LIMIT 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'aditya.patel@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'O_POS' LIMIT 1 OFFSET 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'kabir.mehta@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'O_POS' LIMIT 1 OFFSET 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'aarav.sharma@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'A_POS' LIMIT 1 OFFSET 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'meera.joshi@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'A_POS' LIMIT 1 OFFSET 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'ananya.iyer@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'B_POS' LIMIT 1 OFFSET 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'rohan.das@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'B_POS' LIMIT 1 OFFSET 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'tejas.k@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'B_POS' LIMIT 1 OFFSET 1), 'PENDING', CURRENT_TIMESTAMP, NULL);
INSERT INTO donation_offers (donor_id, blood_request_id, status, offered_at, responded_at) VALUES ((SELECT id FROM users WHERE email = 'tarun.t@gmail.com'), (SELECT id FROM blood_requests WHERE status = 'OPEN' AND blood_group = 'B_POS' LIMIT 1 OFFSET 1), 'PENDING', CURRENT_TIMESTAMP, NULL);